modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mixins]]
config = "gamblingitems.client.mixins.json"

[[mods]]
modId = "gamblingitems"
version = "${version}"
displayName = "Gambling Items"
authors = "Romalaure"
logoFile = "assets/gamblingitems/icon.png"
displayURL = "https://github.com/tidic84/gambling-items"
description = '''Gambling with your items: trade up, upgrades and cases on an exchange terminal; crash, roulette, blackjack, bingo and slots at casino tables or in a pocket casino.'''

[[dependencies.gamblingitems]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gamblingitems]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
